import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Box from "@mui/material/Box";
import Card from "@mui/material/Card";
import { ThemeClientProvider } from "@/components/Provider/ThemeClientProvider";
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline';
import Button from "@mui/material/Button";
import Stack  from "@mui/material/Stack";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeClientProvider>
          <Box
            sx={{
              bgcolor: "background.default",
              width: "100%",
              height: "100vh",
              display: "flex",
              alignItems: "center",
              justifyContent: "center"
            }}
          >
            <Card
              sx={{
                width: "80%",
                borderRadius: "1rem",
                padding : "1rem .4rem"
              }}
            >
              {children}
              <Stack direction={"row"} alignItems={"center"} justifyContent={"end"} gap={"1rem"}  sx={{padding: "1rem 2rem" }}>
                <Button
                  variant="outlined"
                  endIcon={<ErrorOutlineIcon />}
                  sx={{
                    border: " 1px solid #88898a",
                    color: "#88898a"
                  }}
                >
                  Need Help
                </Button>
                <Button variant="outlined" >
                  Privacy Policy
                </Button>
              </Stack>
            </Card>
          </Box>
        </ThemeClientProvider>
      </body>
    </html>
  );
}
